### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NodeBase'

### ISSUE THREAD

**Issue by fungs** [MatrixEditor/fsapi-tools#20]
I tried to use the command line fsapi-tools 2.0.0 but got this error both on Python 3.8 and 3.9:

    fsapi-ctl get netremote.sys.info.friendlyName IP
    Traceback (most recent call last):
      File "/path/fsapi-2/bin/fsapi-ctl", line 5, in <module>
        from fsapi.net.cli import main
      File "/path/fsapi-2/lib/python3.9/site-packages/fsapi/net/__init__.py", line 74, in <module>
        from .base import (
      File "/path/.virtualenvs/fsapi-2/lib/python3.9/site-packages/fsapi/net/base.py", line 716, in <module>
        _NodeListItemValue = str | NodeE8 | int | NodeValue
    TypeError: unsupported operand type(s) for |: 'type' and 'NodeBase'

**Comment by MatrixEditor** [comment]
The simplest solution would be to use a newer version of Python, because alternative Syntax for Unions was introduced first in 3.10. In order to continue support for Python 3.8 and 3.9, I suggest to use `typing.Union` instead (an update should be released soon)

**Comment by fungs** [comment]
Didn't try that because the badge says python 3.7+ and in `pyproject.toml` it even lists 3.6.

I have absolutely no issue with using a newer Python version, it's just not on my Linux distribution as a centrally managed executable by default.

**Comment by MatrixEditor** [comment]
It seems that even though `annotations` are enabled this statement remains unaccepted. I will try to release a new version with a fix as soon as possible.
